import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas} from '@react-three/fiber';
import {OrbitControls, Grid, Text} from '@react-three/drei';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
type Report = {frames:number; sharpness:number[]; features:number[]; adjacent_overlaps:{matches:number;score:number}[]; mean_sharpness:number; median_overlap:number; capture_ready:boolean; processing_ms:number};
type Room = {id:string; name:string; x:number; z:number; panorama?:string};
const directions = ['Start at the doorway', 'Turn 45° right', 'Keep 30–50% overlap', 'Tilt upward', 'Tilt downward', 'Finish facing the doorway'];

function Scene({rooms, selected, onSelect}:{rooms:Room[];selected:string;onSelect:(id:string)=>void}) { return <Canvas camera={{position:[7,7,8], fov:48}}><color attach="background" args={['#07111f']}/><ambientLight intensity={1.4}/><directionalLight position={[4,6,3]} intensity={2}/><Grid args={[18,18]} cellColor="#24415b" sectionColor="#3aa6b9"/><OrbitControls/><mesh position={[0,1.5,0]}><boxGeometry args={[7,3,5]}/><meshStandardMaterial color="#10283d" wireframe transparent opacity={.45}/></mesh>{rooms.map(r=><group key={r.id} position={[r.x,.18,r.z]} onClick={()=>onSelect(r.id)}><mesh><cylinderGeometry args={[.34,.34,.18,24]}/><meshStandardMaterial color={r.id===selected?'#f5b642':'#42d3b5'}/></mesh><Text position={[0,.45,0]} fontSize={.25} color="white">{r.name}</Text></group>)}</Canvas> }

function App(){
 const [files,setFiles]=useState<File[]>([]), [report,setReport]=useState<Report|null>(null), [busy,setBusy]=useState(false), [notice,setNotice]=useState('Add 8–20 overlapping photos of one room.'), [step,setStep]=useState(0), [rooms,setRooms]=useState<Room[]>(()=>JSON.parse(localStorage.getItem('f23d-rooms')||'[{"id":"room-1","name":"Living room","x":0,"z":0}]')), [selected,setSelected]=useState('room-1');
 const selectedRoom=rooms.find(r=>r.id===selected); const coverage=useMemo(()=>Math.min(100, Math.round(files.length/18*100)),[files]);
 const persist=(next:Room[])=>{setRooms(next);localStorage.setItem('f23d-rooms',JSON.stringify(next));};
 const request=async(path:string)=>{if(files.length<2){setNotice('Select at least two images.');return;}setBusy(true);try{const data=new FormData();files.forEach(f=>data.append('files',f));const r=await fetch(API+path,{method:'POST',body:data});const json=await r.json();if(!r.ok)throw new Error(json.detail||'Processing failed');return json;}catch(e){setNotice(e instanceof Error?e.message:'Network error');}finally{setBusy(false)}};
 const analyze=async()=>{const result=await request('/analyze');if(result){setReport(result);setNotice(result.capture_ready?'Capture quality is sufficient to stitch.':'Retake low-overlap or blurry frames before stitching.')}};
 const stitch=async()=>{const result=await request('/stitch');if(result) {if(result.success&&selectedRoom){persist(rooms.map(r=>r.id===selected?{...r,panorama:result.panorama}:r));setNotice(`Panorama completed in ${result.processing_ms} ms.`)} else setNotice(result.reason)}};
 const addRoom=()=>{const id='room-'+Date.now();const next=[...rooms,{id,name:'Room '+(rooms.length+1),x:(rooms.length%3-1)*2,z:Math.floor(rooms.length/3)*2}];persist(next);setSelected(id)};
 return <main><header><div><span className="eyebrow">LOCAL-FIRST COMPUTER VISION</span><h1>From<span>2D</span>to<span>3D</span></h1></div><p>Guided capture · measurable quality · panorama · spatial room graph</p></header><section className="layout"><aside><h2>1. Capture a room</h2><label className="drop"><input type="file" accept="image/*" capture="environment" multiple onChange={e=>{setFiles(Array.from(e.target.files||[]));setReport(null)}}/><b>{files.length?`${files.length} photos selected`:'Add room photos'}</b><small>JPG/PNG · photos stay in your browser until you run a job</small></label><div className="coverage"><div style={{width:coverage+'%'}}/><span>{coverage}% capture target</span></div><ol className="guide">{directions.map((d,i)=><li className={i===step?'active':''} onClick={()=>setStep(i)} key={d}>{i+1}. {d}</li>)}</ol><div className="actions"><button onClick={analyze} disabled={busy}>{busy?'Analyzing…':'Analyze quality'}</button><button className="accent" onClick={stitch} disabled={busy||!report?.capture_ready}>Create panorama</button></div><p className="notice">{notice}</p>{report&&<div className="metrics"><b>Capture report</b><span>Sharpness {report.mean_sharpness}</span><span>Median overlap {Math.round(report.median_overlap*100)}%</span><span>Features/frame {Math.round(report.features.reduce((a,b)=>a+b,0)/report.features.length)}</span><span>Analysis {report.processing_ms} ms</span></div>}</aside><section className="workspace"><div className="tabs"><b>2. Spatial model</b><button onClick={addRoom}>+ Room</button><select value={selected} onChange={e=>setSelected(e.target.value)}>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><div className="scene"><Scene rooms={rooms} selected={selected} onSelect={setSelected}/></div><div className="viewer"><div><b>3. Panorama viewer</b><small>{selectedRoom?.panorama?'Drag or scroll this image to inspect it.':'Process a room to add its panorama.'}</small></div>{selectedRoom?.panorama?<img src={selectedRoom.panorama} alt="Generated panorama"/>:<div className="empty">The 3D room is a navigable spatial model. Image stitching produces a panorama—not a metric 3D reconstruction. Depth, SLAM and NeRF are future pipeline stages.</div>}</div></section></section><footer>CV signals: Laplacian blur · ORB features · adjacent matching · OpenCV panorama stitcher. No fabricated AI claims.</footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);
